### PR TITLE
fix #127

### LINKED ISSUE #127: `examples/rocket.mdx` file has an axum example
The `examples/rocket.mdx` file contains an example for rocket but also an example for using axum.

### PR DESCRIPTION
**Pull request by SyedFasiuddin**
closes #127

### CODE REVIEW

**Comment by jonaro00** [comment]
Sadly, the `rocket.mdx` file is not being used at all. Good catch though!

As for the Axum examples, I am overhauling them and their layout in #125. Feedback appreciated.

**Comment by joshua-mo-143** [comment]
lgtm, I've pinged ivan already to give this a once over before officially merging

**Comment by SyedFasiuddin** [comment]
> Sadly, the `rocket.mdx` file is not being used at all. Good catch though!
> 
> As for the Axum examples, I am overhauling them and their layout in #125. Feedback appreciated.

Ah, yes. I think I will not add anything in axum file, your PR does that. this PR will then only remove axum example from rocket file.

**Comment by jonaro00** [comment]
I read on Mintlify docs that the rocket page is accessible via URL, but does not appear in the sidebar unless mint.json is updated accordingly.
Btw, (for Ivan also), were we going to add back the Rocket page(s)? There seems to be reasonable amount of discussion about it in Discord. (regarding popularity)

**Comment by ivancernja** [comment]
@jonaro00 lets do it. I can sort it out in a week or two or if anyone has the time to get them back up, we'd appreciate it! Iirc the rocket.mdx should contain everything there was.

**Pull request closed without merging**
