### PR TITLE
feat: Use Mintlify 3. Remove package.json and yarn lock.

### PR DESCRIPTION
**Pull request by jonaro00**
Mintlify 3 has a slightly better installation process, and other improvements.

Downsides with this:
- Was shaky to install on Windows (I switched to WSL and it worked)
- Seems like Node 19 is required
- Deployment needs to be adjsuted?

### CODE REVIEW

**Comment by joshua-mo-143** [comment]
Can't comment personally on this as I don't know what we'd need to do to change the deployment.

Node 18 itself will be reaching LTS maintenance mode from 2023/10/18 so we have some time to upgrade. Mintlify itself has always been a bit shaky for me to install on Windows though so :shrug:

**Comment by jonaro00** [comment]
(Ivan will know this, but) If we are using Mintlify's integrated deployment, they already use the latest version. In that case  we *should*  upgrade in order to keep parity between local dev and prod.

**Comment by jonaro00** [comment]
I simply relayed their new installation instructions to this. Upgrading package.json never worked for me.

**Comment by oddgrd** [comment]
Oh, interesting. Meaning updating package.json, running `yarn (install)` and then `yarn mintlify dev` did not work? Did it give you a weird 404 error?

**Comment by joshua-mo-143** [comment]
I got 404 errors while using Node v20. Downgrading to v18 via nvm worked for me.

I did look on their discord and saw apparently they want v19 or something to be able to run Mintlify 3.

**Comment by jonaro00** [comment]
> not need to globally install

It feels like Mintlify is kind of a "only latest version supported" type of thing. They handle deployment and seem to upgrade the deployed version regardless of what the devs used. (Has managed to keep good backwards compatibility it seems)

Not perfect, but can justify a global install.

**Pull request merged**
