### PR TITLE
docs: create getting-started move relevant content

### PR DESCRIPTION
**Pull request by sentinel1909**
This is a pull request in support of Issue #166 that I opened for shuttle-hq/shuttle-docs. I created a new Getting Started menu group and moved the relevant content from the Introduction menu group.

This now surfaces the Getting Started content more clearly and makes it available at a glance.

### CODE REVIEW

**Comment by joshua-mo-143** [comment]
Requested review as I'd like to get a second opinion on whether we think this will actually enhance our documentation or not

**Comment by sentinel1909** [comment]
Oof...this was my bad, sorry folks. I was doing some rearranging with my forked repos and ended up deleting this by mistake.  Sounds like it wasn't entirely necessary anyway.  Let me know if I need to redo it.

**Comment by jonaro00** [comment]
Well, we can't see the changes anymore, so we can't do much. Best hope is if you still have your fork cloned locally. Then you can recreate the repo and recover.

**Comment by sentinel1909** [comment]
I do have it all on another computer, will get it back up this evening.

**Pull request closed without merging**
