### PR TITLE
Separate examples by sub-pages. Update all examples. Add back Poise. Minor fixes.

### LINKED ISSUE #86: Put framework examples in separate sub-pages
The current framework example pages have several example projects listed on the same page, requiring scrolling to see the more advanced ones.

image

The docs menu (left pane) can be re-arranged into one sub-page for each example (image from a different docs site using the same docs framework):

image

Some sections that subpages have in common (think "Prerequisites"), might want a separate page, and a reference like "See the ___  page first".

### PR DESCRIPTION
**Pull request by jonaro00**
Draft for #86 and other fixes.
I put each example on a sub-page, updated the examples, and added the Cargo.toml file aswell.
The examples are from https://github.com/shuttle-hq/shuttle-examples/pull/60.

image
image

If this looks good, I can continue doing this for Actix and Serenity.

Closes #86

### CODE REVIEW

**Comment by ivancernja** [comment]
Hey @jonaro00, thanks for this, looks very clean!

I have a couple of questions:
1. I might be out of the loop but why are we moving the contributing part of it over to GH? For easing maintenance? 
2. I saw you've added some icons on various spots but when trying to run your changes locally, nothing pops up.
3. Some links in the sidebar are now "empty" -- eg. if I click on "Contributing", I get an empty docs page
4. What is supposed to go under 'All Examples'?

Other than that, thanks for also sorting out some of the minor things such as changing 'API Docs' to 'Crate Docs' and others!

**Comment by jonaro00** [comment]
1. Mainly that but also that the graph fails to render on the webpage.
2-4. Oh, it seems like I was using a bunch of Mintlify 3 features without knowing. I used v3 locally when introducing these. I guess #130 is needed before this, but you can try it locally if you upgrade. The icons will then show up, it's just plain font-awesome. Let me know if they are fitting or not, or if all pages should have icons etc. The "empty" links you got will correctly link to the external page in v3. All Examples link to the examples repo.

The Crate Docs name is tricky. It links to runtime docs, but we have so many crates... But that one can be considered a homepage. maybe add links to the other's docs in there.

**Comment by ivancernja** [comment]
1. That's fine. We can check with Mintlify whether they can add mermaid support if that was the deal breaker :)
2 - 4. I'll comment that over there.

re: Crates docs - let's keep it this way for now (linking to the runtime docs)

**Comment by ivancernja** [comment]
@jonaro00 lmk when this is ready for final review! :)

**Comment by jonaro00** [comment]
I think it is. There should not be any major v3 additions in here now. (If there are, they will work in production anyways :P)

**Pull request merged**
