### PR TITLE
docs: add documentation for rocket dyn_template example

### PR DESCRIPTION
**Pull request by jhawkesworth**
Documentation for shuttle docs site for the example that was recently merged under https://github.com/shuttle-hq/examples/pull/38

### CODE REVIEW

**Comment by jhawkesworth** [comment]
@oddgrd documentation as requested.

**Comment by joshua-mo-143** [comment]
@oddgrd Apologies for the re-ping but it looks like this has been open for quite a while with no update - should we be merging this in accordance with the previously merged PR for shuttle-examples?

**Comment by oddgrd** [comment]
Oh, sorry @jhawkesworth! I saw this way back but then forgot to get back to it. I'm not sure we can merge this now since the docs for rocket have been mostly pulled out. I believe this is up for discussion though, so we could consider including this if we bring rocket docs back to the front.

**Comment by jhawkesworth** [comment]
As things stand the core team have more important things to get done so let's close this. Sometimes PRs just arrive at the wrong moment.

**Pull request closed without merging**
