### PR TITLE
docs: add troubleshooting section to static folder page

### PR DESCRIPTION
**Pull request by joshua-mo-143**
- Adds a troubleshooting section to the `shuttle-static-folder` page.

(footnote: the middle commit was supposed to be "add troubleshooting section to static folder page", not sure why it's done that)

### CODE REVIEW

**Comment by ivancernja** [comment]
Thanks for this @joshua-mo-143 . Before we move forward on the PR; @oddgrd can we rather implement error handling here?

**Comment by joshua-mo-143** [comment]
Maybe it might be tied to the whole Git thing? If there's no files in a folder when you try to commit a Git branch, it doesn't detect the folder as being there.

**Comment by jonaro00** [comment]
Or just prioritize this ;) https://github.com/shuttle-hq/shuttle/pull/1050

**Comment by ivancernja** [comment]
@oddgrd lmk your thoughts on @jonaro00's comment above :)

**Comment by oddgrd** [comment]
I am a fan of the idea of removing the static folder, but as for whether or not to prioritize this PR now, I think we should discuss that in our planning sessions on Monday.

**Comment by joshua-mo-143** [comment]
Closed as this currently serves no use and if we're working on not requiring `shuttle-static-folder` already, there is not much point in adding disclaimers or troubleshooting.

**Pull request closed without merging**
